volumes:
  lusmu-db:

services:
  lusmu:
    container_name: lusmu-dev
    build: app/
    environment:
      NODE_ENV: development
    env_file:
      - .env.development
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/test:/usr/src/app/test
    command: npm run watch
    depends_on:
      - db

  db:
    container_name: lusmu-db
    image: postgres:14.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - lusmu-db:/var/lib/postgresql/data
