volumes:
  lusmu-db:

services:
  lusmu:
    container_name: lusmu-dev
    build: app/
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/test:/usr/src/app/test
    depends_on:
      - db

  db:
    container_name: lusmu-db
    image: postgres:14.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - lusmu-db:/var/lib/postgresql/data

  e2e:
    container_name: lusmu-e2e
    build: e2e/
    volumes:
      - ./e2e/cypress:/e2e/cypress
