volumes:
  lusmu-db:

services:
  lusmu:
    container_name: lusmu-dev
    build: app/
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/test:/usr/src/app/test
    depends_on:
      - db

  lusmu-nest:
    container_name: lusmu-nest
    build: app-nest/
    environment:
      NODE_ENV: development
      DATABASE_HOST: db
      DATABASE_NAME: nest
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - ./app-nest/src:/usr/src/app/src
      - ./app-nest/test:/usr/src/app/test
    depends_on:
      - db

  db:
    container_name: lusmu-db
    image: postgres:14.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - lusmu-db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
