version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - '5432:5432'
    volumes:
      - hytuslain-db:/var/lib/postgresql/data

  hytuslain:
    image: hytuslain
    environment:
      DB_SCHEMA: ${DB_SCHEMA:-postgres}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: ${DB_HOST:-postgres}
      SLACK_APP_TOKEN:
      SLACK_BOT_TOKEN:
      SLACK_SIGNING_SECRET:
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  hytuslain-db:
