name: Build and upload image

on:
  workflow_call:

jobs:
  build:
    name: Build and upload image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: app
          tags: hybridilusmu
          outputs: type=docker,dest=/tmp/hybridilusmu.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hybridilusmu
          path: /tmp/hybridilusmu.tar

  build-nest:
    name: Build and upload image (Nest.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: app-nest
          tags: hybridilusmu-nest
          outputs: type=docker,dest=/tmp/hybridilusmu-nest.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hybridilusmu-nest
          path: /tmp/hybridilusmu-nest.tar
