name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    environment: Docker deployment

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hytuslain/hytuslain:$(date +%s)

    - name: Docker Push
      run: docker push hytuslain/hytuslain
