name: Push (main)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build_image.yaml

  tests:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml
    needs:
      - build

  # FIXME: Re-enable once org permissions have been fixed.
  # publish:
  #   name: Publish image
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #     - tests
  #   steps:
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: hybridilusmu
  #         path: /tmp
  #     - name: Load image
  #       run: docker load --input /tmp/hybridilusmu.tar
  #     - name: Login to GHCR
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Tag image
  #       run: docker tag hybridilusmu ghcr.io/funidata/hybridilusmu:next
  #     - name: Push image to GHCR
  #       run: docker push ghcr.io/funidata/hybridilusmu:next
