name: Push (other branches)

on:
  push:
    branches-ignore:
      - main
  merge_group:

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build_image.yaml

  tests:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml
    needs:
      - build
