name: Push (other branches)

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/image.yaml

  tests:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml
    needs:
      - build
