name: Release new version

on:
  release:
    types:
      - released

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build_image.yaml

  tests:
    name: Run tests
    uses: ./.github/workflows/run_tests.yaml
    needs:
      - build

  publish:
    name: Publish image
    runs-on: ubuntu-latest
    needs:
      - build
      - tests
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Parse version number from package.json
        id: semver
        run: echo "::set-output name=version::$(cat package.json | jq '.version' | tr -d '"')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: hybridilusmu
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/hybridilusmu.tar
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag image
        run: |
          docker tag hybridilusmu ghcr.io/funidata/hybridilusmu:${{ steps.semver.outputs.version }}
          docker tag hybridilusmu ghcr.io/funidata/hybridilusmu:latest
      - name: Push image to GHCR
        run: docker push --all-tags ghcr.io/funidata/hybridilusmu

  publish-docs:
    name: Publish documentation
    uses: ./.github/workflows/release_docs.yaml
    needs:
      - publish
    permissions:
      pages: write
      id-token: write
