name: Deploy documentation

on:
  # FIXME: For testing.
  push:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build vuepress project
        working-directory: docs
        run: npm run build
      - name: Upload gh-pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/build

  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs:
      - build-docs
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy artifact to GH Pages
        uses: actions/deploy-pages@v2
