name: Run tests

on:
  workflow_call:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: npm run init
      - name: Run linter
        working-directory: app
        run: npm run lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: hybridilusmu
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/hybridilusmu.tar
          docker image ls -a
      - name: Run unit tests
        run: docker compose -f compose.yaml -f compose-ci.yaml run lusmu npm test
      - name: Stop containers
        if: always()
        run: npm stop

  unit-tests-nest:
    name: Unit tests (Nest.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: hybridilusmu-nest
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/hybridilusmu-nest.tar
          docker image ls -a
      - name: Run unit tests
        run: docker compose -f compose.yaml -f compose-ci.yaml run lusmu-nest npm test
      - name: Stop containers
        if: always()
        run: npm stop

  integration-tests-nest:
    name: Integration tests (Nest.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: hybridilusmu-nest
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/hybridilusmu-nest.tar
          docker image ls -a
      - name: Run integration tests
        run: docker compose -f compose.yaml -f compose-ci.yaml run lusmu-nest npm run test:integration
      - name: Stop containers
        if: always()
        run: npm stop
