name: Run tests

on:
  push:

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # - name: Build and export
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: app
      - name: Start containers
        run: npm start
      - name: Run unit tests
        run: npm test
      - name: Stop containers
        run: npm stop
