name: Run tests

on:
  workflow_call:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: npm run init
      - name: Run linter
        working-directory: app
        run: npm run lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: hybridilusmu
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/hybridilusmu.tar
          docker image ls -a
      - name: Start containers
        run: docker compose -f compose.yaml -f compose-ci.yaml up -d lusmu
      - name: Run unit tests
        run: npm test
      - name: Stop containers
        if: always()
        run: npm stop
# FIXME: Enable these once integration tests exit cleanly.
# integration-tests:
#   name: Integration tests
#   runs-on: ubuntu-latest
#   needs: build
#   steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2
#     - name: Download artifact
#       uses: actions/download-artifact@v3
#       with:
#         name: hybridilusmu
#         path: /tmp
#     - name: Load image
#       run: |
#         docker load --input /tmp/hybridilusmu.tar
#         docker image ls -a
#     - name: Start containers
#       run: docker compose -f compose.yaml -f compose-ci.yaml up -d lusmu
#     - name: Run integration tests
#       run: npm run test:integration
#     - name: Stop containers
#       run: npm stop
